### ISSUE TITLE
Consider to replace hardcoded hooks with a cleaner approach

### ISSUE THREAD

**Issue by nightroman** [RedeployAB/PSScaffold#1]
@KarlGW, it is a great project! Tried commands work like a charm and generated
templates are handy and very neat. I am very glad that Invoke-Build is used as
the task runner.

As far as Invoke-Build is used, I would like to recommend an approach that will
make generated build templates much cleaner. It is explained in https://github.com/Xainey/xainey.github.io/issues/1

I understand that the original idea and *implementation* of hooks comes from
*Plaster*. There is nothing wrong with this. And for *Plaster*, which uses
*psake*, it is probably the only way of introducing hooks.

With Invoke-Build these hooks are simply redundant. Yes, they may be removed
from the main generated build script. At the same time users still can add
their hook tasks in *X.settings.ps1* using Invoke-Build `-Before` and `-After`
task parameters. This was exactly designed for scenarios like PSScaffold.

It would be nice to add *commented out* hooks to generated *X.settings.ps1*,
so that users know what they can do. But in many cases they will probably
just remove them still keeping in mind or leave them commented out.
(For example, how many hooks did you actually implement?)

Please do not get me wrong. I have no intent to criticize the current approach.
If you think it is right then let it be, you are the author. I just worry that the
generated scripts introduce some sort of practice and this "recommended"
practice is suboptimal with Invoke-Build used as the build engine.

**Comment by KarlGW** [comment]
@nightroman thank you very much for your feedback! I am very grateful for it, and I will take it into heart and read the provided link. Xainey's blog post about the build pipeline is very good and I trust he will have some good insights in that article. I will look into it before the next release.

I myself need to delve deeper into Invoke-Build since I'm fairly new to it, but realized how tedious it would be to create these files time after time again. So I still have a bit to learn about that module and it's functionalities.

I'll also provide some more "guidance" in the README and tips on what files that are supposed to be modified etc and how to customize it further.

Once again. Thank you for the feedback!

**Comment by KarlGW** [comment]
I have removed the removed the Before and After hooks on each task in the build template. The hooks in the settings template has been out-commented as well. It's now up to the user to fill these out after their own needs.

**Comment by nightroman** [comment]
It is very good.

**Comment by nightroman** [comment]
@KarlGW Do you mind if I refer to this project in some discussions?

**Comment by KarlGW** [comment]
@nightroman Go ahead! Be free to refer to this project.
